version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Dependencies
          command: pip3 install --user circleci -r requirements.txt
  test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          command: python3.7 -B -m unittest discover -s tests -t .
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
