version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Dependencies
          command: pip3 install -r requirements.txt
  test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          command: nosetests tests/
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
